// ── ESG 材料維護 資料模型 ──────────────────────────────────────────────────────

export interface EsgMaterialRecord {
  id: number;
  /** 材料名（繁中） */
  nameTw: string;
  /** 材料名（簡中） */
  nameCn: string;
  /** 材料名（英文） */
  nameEn: string;
  /** 碳排量（kg CO₂e） */
  carbonEmission: number;
  /** 建檔者（姓名） */
  createdBy: string;
  /** 建檔日期（YYYY/MM/DD） */
  createdAt: string;
  /** 最後修改者 */
  updatedBy?: string;
  /** 最後修改日期 */
  updatedAt?: string;
}

// ── Mock 資料（110筆）────────────────────────────────────────────────────────
export const MOCK_ESG_MATERIALS: EsgMaterialRecord[] = [
  { id: 1,   nameTw: '水',                      nameCn: '水',                      nameEn: 'water',                                    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 2,   nameTw: '不鏽鋼',                  nameCn: '不锈钢',                  nameEn: 'Stainless steel',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 3,   nameTw: '鋼',                      nameCn: '钢',                      nameEn: 'steel',                                    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 4,   nameTw: '鑄鐵或生鐵',              nameCn: '铸铁或生铁',              nameEn: 'cast iron or pig iron',                    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 5,   nameTw: '金',                      nameCn: '金',                      nameEn: 'gold',                                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 6,   nameTw: '鉛',                      nameCn: '铅',                      nameEn: 'lead',                                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 7,   nameTw: '鉑',                      nameCn: '铂',                      nameEn: 'platinum',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 8,   nameTw: '銀',                      nameCn: '银',                      nameEn: 'silver',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 9,   nameTw: '銅',                      nameCn: '铜',                      nameEn: 'copper',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 10,  nameTw: '鉻',                      nameCn: '铬',                      nameEn: 'chromium',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 11,  nameTw: '鋅',                      nameCn: '锌',                      nameEn: 'zinc',                                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 12,  nameTw: '鋁',                      nameCn: '铝',                      nameEn: 'aluminum',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 13,  nameTw: '錫',                      nameCn: '锡',                      nameEn: 'tin',                                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 14,  nameTw: '鎳',                      nameCn: '镍',                      nameEn: 'nickel',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 15,  nameTw: '鎘',                      nameCn: '镉',                      nameEn: 'cadmium',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 16,  nameTw: '碳化矽',                  nameCn: '碳化矽',                  nameEn: 'silicon carbide',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 17,  nameTw: '多晶矽',                  nameCn: '多晶矽',                  nameEn: 'Polycrystalline silicon',                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 18,  nameTw: '醋酸',                    nameCn: '醋酸',                    nameEn: 'acetic acid',                              carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 19,  nameTw: '檸檬酸',                  nameCn: '柠檬酸',                  nameEn: 'citric acid',                              carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 20,  nameTw: '硫酸',                    nameCn: '硫酸',                    nameEn: 'sulfuric acid',                            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 21,  nameTw: '磷酸',                    nameCn: '磷酸',                    nameEn: 'Phosphoric acid',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 22,  nameTw: '鹽酸',                    nameCn: '盐酸',                    nameEn: 'hydrochloric acid',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 23,  nameTw: '氟化氫',                  nameCn: '氟化氢',                  nameEn: 'hydrogen fluoride',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 24,  nameTw: '硝酸',                    nameCn: '硝酸',                    nameEn: 'Nitric acid',                              carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 25,  nameTw: '氫氧化鈉',                nameCn: '氢氧化钠',                nameEn: 'sodium hydroxide',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 26,  nameTw: '硝酸銨',                  nameCn: '硝酸铵',                  nameEn: 'Ammonium nitrate',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 27,  nameTw: '氫氧化鉀',                nameCn: '氢氧化钾',                nameEn: 'Potassium hydroxide',                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 28,  nameTw: '雙氧水/過氧化氫',          nameCn: '双氧水/过氧化氢',          nameEn: 'Hydrogen peroxide/hydrogen peroxide',       carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 29,  nameTw: '碳酸鈉',                  nameCn: '碳酸钠',                  nameEn: 'Sodium carbonate',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 30,  nameTw: '氨水',                    nameCn: '氨水',                    nameEn: 'Ammonia water',                            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 31,  nameTw: '氯化鈣',                  nameCn: '氯化钙',                  nameEn: 'calcium chloride',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 32,  nameTw: '酚醛樹脂',                nameCn: '酚醛树脂',                nameEn: 'Phenolic Resin',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 33,  nameTw: '環氧樹脂',                nameCn: '环氧树脂',                nameEn: 'Epoxy resin',                              carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 34,  nameTw: '苯',                      nameCn: '苯',                      nameEn: 'benzene',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 35,  nameTw: '苯酚',                    nameCn: '苯酚',                    nameEn: 'phenol',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 36,  nameTw: '甲醇',                    nameCn: '甲醇',                    nameEn: 'Methanol',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 37,  nameTw: '乙醇/酒精',               nameCn: '乙醇/酒精',               nameEn: 'ethanol/alcohol',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 38,  nameTw: '異丙醇',                  nameCn: '异丙醇',                  nameEn: 'Isopropyl alcohol',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 39,  nameTw: '乙二醇',                  nameCn: '乙二醇',                  nameEn: 'Ethylene glycol',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 40,  nameTw: '丙烯酸丁酯',              nameCn: '丙烯酸丁酯',              nameEn: 'Butyl acrylate',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 41,  nameTw: '3-甲氧基丙酸甲酯',        nameCn: '3-甲氧基丙酸甲酯',        nameEn: 'Methyl 3-methoxypropionate',               carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 42,  nameTw: '丙二醇甲醚',              nameCn: '丙二醇甲醚',              nameEn: 'Propylene glycol methyl ether',            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 43,  nameTw: '二苯醚',                  nameCn: '二苯醚',                  nameEn: 'diphenyl ether',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 44,  nameTw: '丙酮',                    nameCn: '丙酮',                    nameEn: 'acetone',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 45,  nameTw: '丁酮',                    nameCn: '丁酮',                    nameEn: 'Butanone',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 46,  nameTw: 'N-甲基吡咯酮',            nameCn: 'N-甲基吡咯酮',            nameEn: 'N-Methylpyrrolidone',                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 47,  nameTw: '甲基異丁基酮',            nameCn: '甲基异丁基酮',            nameEn: 'Methyl isobutyl ketone',                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 48,  nameTw: '氦氣',                    nameCn: '氦气',                    nameEn: 'Helium',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 49,  nameTw: '二氧化碳',                nameCn: '二氧化碳',                nameEn: 'carbon dioxide',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 50,  nameTw: '一氧化碳',                nameCn: '一氧化碳',                nameEn: 'carbon monoxide',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 51,  nameTw: '氯氣',                    nameCn: '氯气',                    nameEn: 'Chlorine',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 52,  nameTw: '氫氣',                    nameCn: '氢气',                    nameEn: 'hydrogen',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 53,  nameTw: '氬氣',                    nameCn: '氩气',                    nameEn: 'Argon',                                    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 54,  nameTw: '氮氣',                    nameCn: '氮气',                    nameEn: 'Nitrogen',                                 carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 55,  nameTw: '甲烷',                    nameCn: '甲烷',                    nameEn: 'Methane',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 56,  nameTw: '氨氣',                    nameCn: '氨气',                    nameEn: 'Ammonia',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 57,  nameTw: '氧氣',                    nameCn: '氧气',                    nameEn: 'oxygen',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 58,  nameTw: '磷化氫',                  nameCn: '磷化氢',                  nameEn: 'Phosphine',                                carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 59,  nameTw: '砷化氫',                  nameCn: '砷化氢',                  nameEn: 'arsine',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 60,  nameTw: '六氟化硫',                nameCn: '六氟化硫',                nameEn: 'Sulfur hexafluoride',                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 61,  nameTw: '三氟甲烷',                nameCn: '三氟甲烷',                nameEn: 'trifluoromethane',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 62,  nameTw: '矽烷',                    nameCn: '矽烷',                    nameEn: 'Silane',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 63,  nameTw: '三氟化硼',                nameCn: '三氟化硼',                nameEn: 'Boron trifluoride',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 64,  nameTw: '紙箱/瓦楞紙板',           nameCn: '纸箱/瓦楞纸板',           nameEn: 'Carton/corrugated version',                carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 65,  nameTw: '紙板（芯紙）',             nameCn: '纸板（芯纸）',             nameEn: 'Cardboard (core paper)',                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 66,  nameTw: '一般用紙',                nameCn: '一般用纸',                nameEn: 'general paper',                            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 67,  nameTw: '回收紙',                  nameCn: '回收纸',                  nameEn: 'recycled paper',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 68,  nameTw: '低密度聚乙烯_LDPE',       nameCn: '低密度聚乙烯_LDPE',       nameEn: 'Low density polyethylene_LDPE',            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 69,  nameTw: '高密度聚乙烯_HDPE',       nameCn: '高密度聚乙烯_HDPE',       nameEn: 'High density polyethylene_HDPE',           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 70,  nameTw: '聚丙烯_PP',               nameCn: '聚丙烯_PP',               nameEn: 'Polypropylene_PP',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 71,  nameTw: '聚苯乙烯_PS',             nameCn: '聚苯乙烯_PS',             nameEn: 'Polystyrene_PS',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 72,  nameTw: '聚氯乙烯_PVC',            nameCn: '聚氯乙烯_PVC',            nameEn: 'Polyvinyl chloride_PVC',                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 73,  nameTw: '聚對苯二甲酸乙二酯_PET',  nameCn: '聚对苯二甲酸乙二酯_PET',  nameEn: 'Polyethylene terephthalate_PET',           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 74,  nameTw: '聚碳酸酯_PC',             nameCn: '聚碳酸酯_PC',             nameEn: 'Polycarbonate_PC',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 75,  nameTw: '醋酸乙烯共聚物_EVA',      nameCn: '醋酸乙烯共聚物_EVA',      nameEn: 'Vinyl acetate copolymer_EVA',              carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 76,  nameTw: '聚醯胺尼龍或PA或Nylon',   nameCn: 'PA或Nylon',               nameEn: 'Polyamide nylon or nylon_PA or Nylon',    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 77,  nameTw: '炬石風_PSU',              nameCn: '炬石风_PSU',              nameEn: 'Ju Shi Feng_PSU',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 78,  nameTw: '熱可塑性彈性體_PPS',      nameCn: '热可塑性弹性体_PPS',      nameEn: 'According to olefin elastomer_PPS',        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 79,  nameTw: 'FlexPU_PU',              nameCn: 'FlexPU_PU',              nameEn: 'FlexPU_PU',                               carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 80,  nameTw: 'Rigid PU_PU',            nameCn: 'Rigid PU_PU',            nameEn: 'Rigid PU_PU',                             carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 81,  nameTw: '聚乳酸_PLA',             nameCn: '聚乳酸_PLA',             nameEn: 'Polylactic acid_PLA',                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 82,  nameTw: '碳纖製品',               nameCn: '碳纤制品',               nameEn: 'Carbon fiber products',                    carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 83,  nameTw: '鋰電池',                 nameCn: '锂电池',                 nameEn: 'Lithium battery',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 84,  nameTw: 'ABS',                   nameCn: 'ABS',                   nameEn: 'ABS',                                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 85,  nameTw: '保麗龍',                 nameCn: '保丽龙',                 nameEn: 'Styrofoam',                               carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 86,  nameTw: '再生鋁',                 nameCn: '再生铝',                 nameEn: 'Recycled aluminum',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 87,  nameTw: '合成橡膠',               nameCn: '合成橡胶',               nameEn: 'Synthetic rubber',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 88,  nameTw: '二甲苯',                 nameCn: '二甲苯',                 nameEn: 'Xylene',                                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 89,  nameTw: '石油溶劑',               nameCn: '石油溶剂',               nameEn: 'Petroleum solvent',                        carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 90,  nameTw: '矽膠',                   nameCn: '硅胶',                   nameEn: 'Silicone',                                carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 91,  nameTw: '丁腈橡膠',               nameCn: '丁腈橡胶',               nameEn: 'Nitrile rubber',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 92,  nameTw: '乙丙橡膠（EPDM）',       nameCn: '乙丙橡胶（EPDM）',       nameEn: 'Ethylene propylene rubber (EPDM)',          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 93,  nameTw: '熱可塑性橡膠',           nameCn: '热可塑性橡胶',           nameEn: 'Thermoplastic rubber',                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 94,  nameTw: '丁苯橡膠（SBR）',        nameCn: '丁苯橡胶（SBR）',        nameEn: 'Styrene butadiene rubber (SBR)',            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 95,  nameTw: '天然乳膠',               nameCn: '天然乳胶',               nameEn: 'Natural latex',                            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 96,  nameTw: '氯丁二烯橡膠',           nameCn: '氯丁二烯橡胶',           nameEn: 'Chloroprene rubber',                       carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 97,  nameTw: '玻璃纖維',               nameCn: '玻璃纤维',               nameEn: 'Glass fiber',                             carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 98,  nameTw: '壓克力(PMMA)',           nameCn: '压克力(PMMA)',           nameEn: 'Acrylic (PMMA)',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 99,  nameTw: '二氧化矽',               nameCn: '二氧化硅',               nameEn: 'Silicon dioxide',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 100, nameTw: '壓克力樹脂',             nameCn: '压克力树脂',             nameEn: 'Acrylic resin',                            carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 101, nameTw: '聚酯樹脂',               nameCn: '聚酯树脂',               nameEn: 'Polyester resin',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 102, nameTw: '異丁醇',                 nameCn: '异丁醇',                 nameEn: 'Isobutyl alcohol',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 103, nameTw: '庚烷溶劑',               nameCn: '庚烷溶剂',               nameEn: 'Heptane solvent',                          carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 104, nameTw: '碳氫溶劑',               nameCn: '碳氢溶剂',               nameEn: 'Hydrocarbon solvent',                      carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 105, nameTw: '氧化鋁',                 nameCn: '氧化铝',                 nameEn: 'Aluminum oxide',                           carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 106, nameTw: '馬達',                   nameCn: '马达',                   nameEn: 'Motor',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 107, nameTw: '氧化鈦（二氧化鈦）',     nameCn: '氧化钛（二氧化钛）',     nameEn: 'Titanium dioxide',                         carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 108, nameTw: '碳纖紗',                 nameCn: '碳纤纱',                 nameEn: 'Carbon Fiber Yarn / Tow',                  carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 109, nameTw: '碳纖布',                 nameCn: '碳纤布',                 nameEn: 'Carbon Fiber Prepreg',                     carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
  { id: 110, nameTw: '其他',                   nameCn: '其他',                   nameEn: 'other',                                   carbonEmission: 0, createdBy: 'Allen Zou 郝芳筆', createdAt: '2024/03/20' },
];
