/**
 * DateTimeUtils - timezone-aware date formatting
 * MDO timestamps are UTC ISO 8601. Convert to user local timezone.
 */

/** Returns UTC offset label like UTC+8, UTC-5, UTC+5:30 */
export function getUtcOffsetLabel(date: Date = new Date()): string {
  const offsetMin = -date.getTimezoneOffset();
  const sign = offsetMin >= 0 ? '+' : '-';
  const absHour = Math.abs(offsetMin) / 60;
  if (Number.isInteger(absHour)) return `UTC${sign}${absHour}`;
  const h = Math.floor(absHour);
  const m = String((absHour % 1) * 60).padStart(2, '0');
  return `UTC${sign}${h}:${m}`;
}

/**
 * UTC ISO string -> local timezone datetime with offset label
 * e.g. "2026-08-25T23:43:00.000Z" -> "2026/08/26 07:43 (UTC+8)" for Taiwan
 */
export function utcToLocalDisplay(isoString: string | null | undefined): string {
  if (!isoString) return '';
  try {
    const d = new Date(isoString);
    const formatted = new Intl.DateTimeFormat(undefined, {
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', hour12: false,
    }).format(d);
    return `${formatted} (${getUtcOffsetLabel(d)})`;
  } catch {
    return isoString.substring(0, 10).replace(/-/g, '/') + ' ' + isoString.substring(11, 16);
  }
}

/**
 * UTC ISO string -> local timezone date only (YYYY/MM/DD)
 * Handles date boundary correctly (23:30 UTC = next day in UTC+8)
 */
export function utcToLocalDate(isoString: string | null | undefined): string {
  if (!isoString) return '';
  try {
    const d = new Date(isoString);
    return new Intl.DateTimeFormat(undefined, {
      year: 'numeric', month: '2-digit', day: '2-digit',
    }).format(d);
  } catch {
    return isoString.substring(0, 10).replace(/-/g, '/');
  }
}

/**
 * Local Date object -> "YYYY/MM/DD HH:mm (UTC+N)"
 * For timestamps generated by new Date() on the frontend (already local time)
 */
export function localDateToDisplay(date: Date = new Date()): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  const s = `${date.getFullYear()}/${pad(date.getMonth()+1)}/${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
  return `${s} (${getUtcOffsetLabel(date)})`;
}
